name: TypeScript Build and FTP Upload

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install server.js dependencies
      run: npm install
      working-directory: server

    - name: Compile TS server.js
      run: tsc
      working-directory: server

    - name: Webpack server.js
      run: npm run build
      working-directory: server

    - name: Upload server.js
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        onlyNewer: true
        reverse: true
        localDir: './server/dist'
        remoteDir: '${{ secrets.FTP_FOLDER }}/dist'
        options: '--verbose'

    - name: Restart Server Service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        script: ${{ secrets.SSH_COMMAND }}

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Upload frontend
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        onlyNewer: true
        reverse: true
        localDir: './frontend/build'
        remoteDir: '${{ secrets.FTP_FOLDER }}/dist/public'
        options: '--verbose'
